stages:
- name: sonar
  steps:
  - runScriptConfig:
      image: maven:3.6.0-jdk-8-alpine
      shellScript: |-
        mvn sonar:sonar \
          -Dsonar.host.url=http://42.192.99.29/:9000 \
          -Dsonar.login=4d19f62b88e7f3ed0317f657a3f2ece988ebdf73
timeout: 60
notification: {}
